// <auto-generated />
namespace THH.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class modiflog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modiflog));
        
        string IMigrationMetadata.Id
        {
            get { return "201904261042586_modiflog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
